#### <font color='midnightblue'> Important things to discuss:
    - List indexing begins at 0 
    - Python is call by value

### <font color='mediumblue'> Lists

#### <font color='midnightblue'> Example: Indexed

In [3]:
list1 = [10, 12, 14, 16, 18]

print(list1[0])      # Index starts at 0

print(list1[-1])     # Last index at -1

10
18


#### <font color='midnightblue'> Example: Slicable

In [4]:
print(list1[0:3])    # Slicing: exclusive of end value
                     #  i.e. get i=(0, 1, .. n-1)

print(list1[3:])     # "slice from i=3 to end"

[10, 12, 14]
[16, 18]


#### <font color='midnightblue'> Example: Mutable & Mixed Data Types

In [5]:
list1.append(20)
print(list1)

list1.extend([22,24,26])
print(list1)

list1[3]='squirrel'
print(list1)

list1.remove('squirrel')
print(list1)

list1.insert(3,16)
print(list1)

[10, 12, 14, 16, 18, 20]
[10, 12, 14, 16, 18, 20, 22, 24, 26]
[10, 12, 14, 'squirrel', 18, 20, 22, 24, 26]
[10, 12, 14, 18, 20, 22, 24, 26]
[10, 12, 14, 16, 18, 20, 22, 24, 26]


### <font color='mediumblue'> Tuples

#### <font color='midnightblue'> Example: Immutable

In [6]:
tuple1 = (10, 12, 14, 16, 18)
print(tuple1)
print(tuple1[0])
print(tuple1[1:3])
print(tuple1[3:])

tuple1.append(20)
print(tuple1)

(10, 12, 14, 16, 18)
10
(12, 14)
(16, 18)


AttributeError: 'tuple' object has no attribute 'append'

#### <font color='midnightblue'> Example: Lists of tuples

In [ ]:
listoftuples=[tuple1[:3], tuple1[3:]]
print(listoftuples)

#### <font color='midnightblue'> Example: Tuples are faster

In [ ]:
%timeit tuple1=(10,12,14,16,18)
%timeit list1=[10,12,14,16,18]
#%timeit tuple1[3:]
#%timeit list1[3:]

#### <font color='midnightblue'> Example: Unpacking Tuples

In [ ]:
tuple2 = 'Lucy','Ryan'
a, b = tuple2
print('{} is OK, {} is amazing!'.format(a, b))

b, a = a, b
print('{} is OK, {} is amazing!'.format(a, b))

### <font color='mediumblue'> Numpy Arrays

#### <font color='midnightblue'> Example: How to use

In [7]:
# To use numpy, we first have to import the package
import numpy as np

# Can convert a list to an array:
array1=np.array(list1)
print(array1)


# Can make an evenly spaced array between 2 values using linspace or arange.
# linspace takes the number of points to use as an argument and returns floats by default
print(np.linspace(0, 10, 11))

# arange takes the spacing as an argument and returns the type given as the spacing, e.g.
print(np.arange(0, 11, 1.)) 
print(np.arange(0, 11, 1))

[10 12 14 16 18 20 22 24 26]
[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
[  0.   1.   2.   3.   4.   5.   6.   7.   8.   9.  10.]
[ 0  1  2  3  4  5  6  7  8  9 10]


#### <font color='midnightblue'> Example: Useful functions

In [8]:
print('The average of array1 is', np.average(array1))
print('The sum of array1 is', np.sum(array1))

# Apply functions
print(np.exp(array1))
print(np.reciprocal(array1))

array2=np.array([float(array1[i]) for i in range(len(array1))])
a=np.reciprocal(array2)

print(np.reciprocal([float(array1[i]) for i in range(len(array1))]))

angles=np.array([0, np.pi/2., np.pi, 3*np.pi/4.])
np.sin(angles)


The average of array1 is 18.0
The sum of array1 is 162
[  2.20264658e+04   1.62754791e+05   1.20260428e+06   8.88611052e+06
   6.56599691e+07   4.85165195e+08   3.58491285e+09   2.64891221e+10
   1.95729609e+11]
[0 0 0 0 0 0 0 0 0]
[ 0.1         0.08333333  0.07142857  0.0625      0.05555556  0.05
  0.04545455  0.04166667  0.03846154]


array([  0.00000000e+00,   1.00000000e+00,   1.22464680e-16,
         7.07106781e-01])

 #### <font color='midnightblue'> Example: 2d Arrays

In [20]:
M1 = np.array([[2,3],[6,3]])
M2 = np.array([[5,6],[2,9]])

print('M1:')
print(M1)

print('M2:')
print(M2)

M1:
[[2 3]
 [6 3]]
M2:
[[5 6]
 [2 9]]


In [21]:
M3 = M1 * M2            # Element-wise multiplication
print(M3, '\n')

M4 = np.dot(M1, M2)     # Matrix multiplication
print(M4)

[[10 18]
 [12 27]] 

[[16 39]
 [36 63]]


In [9]:
M1 .* M2

SyntaxError: invalid syntax (<ipython-input-9-c37ace85f0a6>, line 1)

### <font color='mediumblue'> Dictionaries

#### <font color='midnightblue'> Example: How to use

In [10]:
price_table = {'apples': 50, 'pears': 60, 'bananas': 20}
print(price_table)

fruit = [('apples', 50), ('bananas', 20), ('pears', 60)]
price_table1 = dict(fruit)
print(price_table==price_table1)

# NOTE: the order when you define a dictionary doesn't matter, it's ordered with a hashtable not 
# with indexing lists and tuples

# To get a value out, you use square brackets but instead of an index, you use the key:
akey = 'apples'
print("The price of {} is {}p.".format(akey, price_table[akey]))

# Trying to use an index wouldn't work:
print(price_table[0])

{'apples': 50, 'pears': 60, 'bananas': 20}
True
The price of apples is 50p.


KeyError: 0

In [11]:
price_table.keys()

dict_keys(['apples', 'pears', 'bananas'])

In [62]:
# Example usage: 
shopping_list = [('apples', 50), ('bananas', 20)]
total = 0
for item, quantity in shopping_list:
    price = price_table[item]
    print('Adding {} {} at {}p each.'.format(quantity, item, price))
    total += price * quantity

print('Total shopping cost is £%.2f.' %(total/100.))

Adding 50 apples at 50p each.
Adding 20 bananas at 20p each.
Total shopping cost is £29.00.


#### <font color='midnightblue'> Example: Mutable

In [63]:
price_table['kiwis']=30
print(price_table)

del price_table['bananas']
print(price_table)

price_table['apples']=25
print(price_table)


{'apples': 50, 'pears': 60, 'bananas': 20, 'kiwis': 30}
{'apples': 50, 'pears': 60, 'kiwis': 30}
{'apples': 25, 'pears': 60, 'kiwis': 30}


#### <font color='midnightblue'> Example: Iterating

In [54]:
# Iterating over the dictionary will iterate over its keys
for key in price_table:
    print("{} cost {}p".format(key, price_table[key]))

apples cost 50p
pears cost 60p
bananas cost 20p
kiwis cost 30p


In [51]:
# Or use the items method:
for key, val in price_table.items():
    print("{} cost {}p".format(key, val))

apples cost 50p
pears cost 60p
bananas cost 20p
kiwi cost 30p
kiwis cost 30p


# <font color='dodgerblue'> Functions

#### <font color='midnightblue'> Example: Simple function

In [66]:
def square_root(x):
    """Useful docstring: Calculates and returns square root of x"""
    i = x ** 0.5
    return i


x = 10
y = square_root(x)
print('The square root of {} is {}'.format(x, y))

# We can set a default value to the function 
def square_root(x=20):
    i = x ** 0.5
    return i


print(square_root())

# Loops, functions and appending
mylist = []
for i in range(1,5):
    mylist.append(square_root(i))
print(mylist)

The square root of 10 is 3.1622776601683795
4.47213595499958
[1.0, 1.4142135623730951, 1.7320508075688772, 2.0]


#### <font color='midnightblue'> Example: Arguments and mutability

In [67]:
def update_integer(i):
    # attempt to update i (integers) are immutable
    i += 1

def update_list_end(arglist):
    arglist[-1] = 50   # Lists are mutable: updates args directly!

a = 1
update_integer(a)
print(a)

mylist = [0, 1, 2, 3, 4]
update_list_end(mylist)
print(mylist)

1
[0, 1, 2, 3, 50]


# <font color='dodgerblue'> Plotting
### <font color='mediumblue'> Matplotlib
#### <font color='midnightblue'> Example: Simple Plot

In [38]:
import matplotlib.pyplot as plt

x = np.linspace(0, 2*np.pi)
y = np.sin(x)

fig = plt.figure(figsize=(12, 5))
ax = fig.add_subplot(111)
ax.plot(x, y,'o-')
ax.margins(0.1)
ax.set_title('2D plot')
ax.set_xlabel('$x$')
ax.set_ylabel(r'$sin(x)$')
ax.plot()


[]

#### <font color='midnightblue'> Example: Labels, ticks and other appenditories

In [68]:
xtick_values = np.linspace(0, 2*np.pi, 5)
xtick_labels = ['$0$', r'$\frac{\pi}{2}$', r'$\pi$', r'$\frac{3\pi}{2}$',
             r'$2\pi$']
fig = plt.figure(figsize=(12, 5))
ax = fig.add_subplot(111); ax.plot(x, y,'-o')
ax.set_title('2D plot')
ax.margins(0.1)
ax.set_xlabel('$x$');  ax.set_ylabel(r'$sin(x)$')
ax.set_xticks(xtick_values)
ax.set_xticklabels(xtick_labels, fontsize=25);